import turtle as t

t.color("red")
t.write("万\n事\n大\n吉", font=("华文行楷", 45, "normal"))
t.penup()
t.goto(80, 0)
t.pendown()
t.write("新\n年\n快\n乐", font=("华文行楷", 45, "normal"))

t.penup()
t.goto(-120, 110)
t.pendown()
t.write("李\n一\n民\n贺", font=("方正舒体", 20, "normal"))

t.penup()
t.goto(-130, 0)
t.color("red")
t.pendown()
t.begin_fill()
t.forward(55)
t.left(90)
t.forward(55)
t.left(90)
t.forward(55)
t.left(90)
t.forward(55)
t.left(90)
t.end_fill()

t.color("white")
t.penup()
t.goto(-100, 0)
t.pendown()
t.write("万\n事", font=("华文隶书", 20, "normal"))
t.penup()
t.goto(-130, 0)
t.pendown()
t.write("如\n意", font=("华文隶书", 20, "normal"))

t.done()